#!/usr/bin/env python3

import argparse
import os
import subprocess


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-o", type=str, required=True)
    overwritten_args, extra_args = parser.parse_known_args()

    orig_output = overwritten_args.o
    root, ext = os.path.splitext(orig_output)
    assert ext in [".wasm", ".js"]
    output = root + ".js"

    if os.path.basename(root) == "solver":
        extra_args += ["-s", "EXPORTED_FUNCTIONS=_solve_puzzle,_malloc,_free"]
    args = ["emcc", "-o", output] + extra_args
    subprocess.check_call(args)


if __name__ == "__main__":
    main()
