name: Build logic-pad-solver-core

on:
  push:
    branches: ["main"]
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name: Setup build environment
      run: |
        rustup target add wasm32-unknown-emscripten
        rustup update
        cd ${{ runner.temp }}
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
    - uses: actions/checkout@v4
      with:
        path: logic-pad-solver
    - name: Clone cspuz_core
      run: git clone --recursive https://github.com/semiexp/cspuz_core.git cspuz_core
    - name: Build
      run: |
        cd logic-pad-solver/packages/logic-pad-solver-core
        npm build-rust
        npm pack
    - uses: actions/upload-artifact@v4
      with:
        name: logic-pad-solver
        path: logic-pad-solver/packages/logic-pad-solver-core/logic-pad-solver-core-*.tgz
